name: Main

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ "3.8", "3.9", "3.10", "3.11" ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.version }}
    - run: pip install -e .
    - run: pytest

  integration-tests:
    env:
      WEAVIATE_VERSION: "1.27.0"
      MODULES: "text2vec-transformers,text2vec-contextionary"
    name: Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ "3.8", "3.9", "3.10", "3.11" ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.version }}
        cache: 'pip' # caching pip dependencies
    - run: pip install -e .
    - name: Start up Weaviate cluster
      uses: weaviate/weaviate-local-k8s@v2
      with:
        workers: 1
        replicas: 1
        weaviate-version: ${{ env.WEAVIATE_VERSION }}
        modules: ${{ env.MODULES }}
    - name: Run unittests
      run: ./test/run_integration_test.sh
